Jai babe Di
Jai Guru Maa Ji

---
title: "R Notebook"
output: html_notebook
---


```{r, message=FALSE, warning=FALSE}
library(Seurat)
library('biomaRt')
library(SeuratDisk)
library(qs)
library(dplyr)
```

```{r}

seu <- qread("/home/garga7/Anjali_data/int_data/Dolan_data/iMGLs_depthnorm_liger_seurat_2024_recluster.qs")

# Add metadata
seu$Integrated_cell_type <- "Homeostatic" 
seu$batch <- "Dolan"

# change assay
DefaultAssay(seu) <- "RNA"

seu <- FindVariableFeatures(seu)
seu[["RNA3"]] <- as(object = seu[["RNA"]], Class = "Assay")
DefaultAssay(seu) <- "RNA3"
seu[["RNA"]] <- NULL
seu <- RenameAssays(object = seu, RNA3 = 'RNA')

#  save files
#SaveH5Seurat(seu, filename = "~/Anjali_data/int_data/Dolan_data/Dolan.h5Seurat", overwrite = T)
#Convert("~/Anjali_data/int_data/Dolan_data/Dolan.h5Seurat", dest = "h5ad", overwrite = T)
```

```{r}

obj <- qread("/home/garga7/Anjali_data/int_data/SRT_mapping/input_file/Allfour_SCT_integration_layer_wdedited_cells_newanno_SCT.qs", nthreads = 6 )


# change assay
DefaultAssay(obj) <- "RNA"

obj <- FindVariableFeatures(obj)
obj[["RNA3"]] <- as(object = obj[["RNA"]], Class = "Assay")
DefaultAssay(obj) <- "RNA3"
obj[["RNA"]] <- NULL
obj <- RenameAssays(object = obj, RNA3 = 'RNA')

#SaveH5Seurat(obj, filename = "~/Anjali_data/int_data/Dolan_data/Allfour.h5Seurat", overwrite = T)
#Convert("~/Anjali_data/int_data/Dolan_data/Allfour.h5Seurat", dest = "h5ad", overwrite = T)

```


```{r}

file <- read.csv("/home/garga7/Anjali_data/int_data/Dolan_data/41590_2023_1558_MOESM3_ESM.csv")

sig_upgene <- file$gene[file$avg_logFC>0] 

common.features <- intersect(rownames(obj), rownames(seu))

common.features2 <- intersect(common.features, sig_upgene) #1525

 seu_sub <- DietSeurat(seu, features = common.features2)
obj_sub <- DietSeurat(obj, features = common.features2)

```

```{r}

# common.features <- intersect(obj@assays$RNA@var.features, seu@assays$RNA@var.features)
# 
# 
# seu_sub <- DietSeurat(seu, features = common.features)
# obj_sub <- DietSeurat(obj, features = common.features)

```


```{r}

#common.features <- intersect(rownames(obj), rownames(seu))

#seu_sub <- DietSeurat(seu, features = common.features)
#obj_sub <- DietSeurat(obj, features = common.features)

```


```{r}
# save the file

int_data_both <- merge(seu_sub, obj_sub)
int_data_both <- NormalizeData(int_data_both)
int_data_both <- FindVariableFeatures(int_data_both)

SaveH5Seurat(int_data_both, filename = "~/Anjali_data/int_data/Dolan_data/int_data_both_upgene.h5Seurat", overwrite = T)
Convert("~/Anjali_data/int_data/Dolan_data/int_data_both_upgene.h5Seurat", dest = "h5ad", overwrite = T)

```


