Jai Babe Di
Jai Guru Maa Ji

---
title: "R Notebook"
output: html_notebook
---


```{r}
library(qs)
library(dplyr)
library(ggplot2)
```


```{r}
sjob <-  qread("/home/garga7/Anjali_data/int_data/Dolan_data/iMGLs_depthnorm_liger_seurat_2024_seurat_predicted_with_humanonly.qs")
```

```{r}
sjob@meta.data %>% colnames()
```


```{r}
p <- sjob@meta.data %>%
            count(Cell_type, predicted.id) %>%
            mutate(frac = n / sum(n)) %>% # % dataset
            # % of cell type
            group_by(Cell_type) %>%
            mutate(frac_cell = n / sum(n)) %>%
            ungroup() %>%
            # % cluster
            group_by(Cell_type) %>%
            mutate(frac_clus = n / sum(n)) %>%
            ungroup() %>%
            ggplot(aes(
                y = Cell_type, x = predicted.id,
               # fill= frac
                #fill = frac_cell
                fill= frac_clus
            )) +
            geom_tile() +
            scale_fill_distiller(palette = "Reds", direction = 1) +
           # coord_fixed() +
            geom_tile(color = "black", lwd = 1) +
            theme(text = element_text(size = 18, face = "bold", colour = "black")) +
            xlab(" Garg et al. clusters") +
            ylab("Dolan et al. clusters")+
            theme(axis.text.x = element_text(angle = 90, hjust = 1))

pdf("/home/garga7/Anjali_data/int_data/Dolan_data/plots/Dolan_data_label_transfer_with_humanonly.pdf", width = 8, height = 6)
p



```

